/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab_2_2.webWork.Poker.src.test.java.Poker;

import lab_2_2.webWork.Poker.src.main.java.Poker.App;
import lab_2_2.webWork.Poker.src.main.java.Poker.Poker;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void shouldReturn_AH_WhenGivePoker_A_H(){
        Poker poker=new Poker('A','H');
        String strPoker=poker.toString();
        Assertions.assertEquals("AH",strPoker);
    }

    @Test void shouldReturn_9_WhenGivePoker_9_D(){
        Poker poker=new Poker('9','D');
        int value=poker.getIDValue();
        Assertions.assertEquals(9,value);
    }

    @Test void shouldReturn_83_WhenGivePoker_J_S(){
        Poker poker=new Poker('J','S');
        int value=poker.getTypeValue();
        Assertions.assertEquals(83,value);
    }
}
